### ISSUE TITLE
Revise requirements

### ISSUE THREAD

**Issue by arneturuc** [timewarrior-synchronize/timew-sync-client#36]
Some required libraries are only included for very specific tasks, like
- formatting code during development (`black`)
- providing backwards compatability with older python versions (`six`)
only to name a few.

The `py` library is only in maintenance mode and replacable by other packages.

For future support it could be a good idea to revise the requirements and remove unnecessary/outdated ones.

**Comment by xPushpeshx** [comment]
#37 has been update kindly check and let me know how else i can help you
